### ISSUE TITLE
newData should contain all the merged data

### ISSUE THREAD

**Issue by georgesboris** [goldibex/targaryen#108]
Hey man, thanks for developing this.

We've been trying to use targaryan for a while now with my team.
Although it helps a lot we're encountering some issues, specially since the updates made recently.

Take a look at this for instance.

In Firebase, when you update some paths, the newData holds all the information for the current tree, not only the information that is been sent.

Like so:

<img width="331" alt="captura de tela 2016-12-22 as 4 49 46 pm" src="https://cloud.githubusercontent.com/assets/3660797/21438226/b0ada300-c866-11e6-9e8b-1d56247f96b2.png">

<img width="1100" alt="captura de tela 2016-12-22 as 4 45 41 pm" src="https://cloud.githubusercontent.com/assets/3660797/21438076/18bbeb7e-c866-11e6-91f4-cdf141b6fbac.png">

When trying to do the same with targaryan:

![captura de tela de 2016-12-22 16-43-08](https://cloud.githubusercontent.com/assets/3660797/21438104/3e92be4a-c866-11e6-80fb-3798e1e7075b.png)

I will try to post here when we find any other issues.
And we will gladly contribute to their solutions, it's just that we're in a crazy end of year sprint.
We're kind of being forced to "let the tests slip for a while" instead of being allowed to fix this.

**Comment by georgesboris** [comment]
Note that when the newData holds any value, like if we were trying to update the `createdBy` prop instead of passing `null` to it, it appears to work as expected.

**Comment by dinoboff** [comment]
Thanks for the report. I could reproduce it and I am working on a fix.

**Comment by dinoboff** [comment]
ps: note that newData reference the all new tree; one location in that tree. It seems there's bug where the parent node got deleted instead of just `createdBy`.

**Comment by dinoboff** [comment]
@georgesboris It should be fixed in 3.0.0-rc.4.
