### ISSUE TITLE
Wrong result for array-like collections

### ISSUE THREAD

**Issue by barmalejj** [goldibex/targaryen#122]
Hey!

Great library! I was looking for something like that, BUT ... it doesn't work well for array-like collections. Example:
lets say we have collection like that:
(We're are using bolt in our project)
```
type SomeAttr {
  // some mandatory property
  itemId: String
  ...
  // some optional property
  someAttrProp: String | Null
  ...
}
type Item {
  ...
  someAttrsCollection: SomeAttr[]
  ...
}
```
This code after compile results with rules like
```
...
"someAttrsCollection": {
  "$key1": {
    ".validate": "newData.hasChildren() && newData.hasChild('itemId')",
    ...
    "someAttrProp": {
      ".validate": "newData.isString()"
    }
    ...
  }
}
...
```
so, if we make write operation like that: `/item/someAttrsCollection/0/someAttrProp, 'some value'` it should be successful (and it is in real database!!!), but unit test with targaryen fails (write is denied) complaining to this rule `".validate": "newData.hasChildren() && newData.hasChild('itemId')"`

**Comment by dinoboff** [comment]
Can you check https://github.com/dinoboff/targaryen/commit/267efe3c9f96db26c2fa75d9502ba1c56f33dc39
; the test passes. How can reproduce your error?

**Comment by barmalejj** [comment]
Here:
```
someAttrsCollection: {
 +            0: {
 +              itemId: 'foo'
 +            }
 +          }
```
is a mistake. *someAttrsCollection* should be an array. Like:
```
someAttrsCollection: [
 +            0: {
 +              itemId: 'foo'
 +            }
 +          ]
```

**Comment by dinoboff** [comment]
Update with data set to to an array... the tests are still passes.

**Comment by dinoboff** [comment]
@barmalejj 

ps: I added an assertion to test the write operation fails if there's no itemId.

**Comment by dinoboff** [comment]
Feel free to reopen if some inconsistent test (as a bare minimum, db data, its rules, and simulation write path and data).
