### ISSUE TITLE
Jest support

### ISSUE THREAD

**Issue by fernandopasik** [goldibex/targaryen#129]
Since there are jasmine matchers do you know if there is a way to use them with jest as well?

**Comment by dinoboff** [comment]
I am not familiar with Jest test suite; I am not sure what kind of api would work with it. Not all test suite require their own plugin, the [default API](https://github.com/goldibex/targaryen#api) might be fine; e.g. tap or ava can use the default API directly (something like the chai plugin would be an anti-pattern), although #124 needs a fix.

What would a Jest test for firebase security rules look like?

**Comment by dinoboff** [comment]
Also, are tests run concurrently?

**Comment by fernandopasik** [comment]
Yes, tests run concurrently.

I've tried to [extend](https://facebook.github.io/jest/docs/en/expect.html#expectextendmatchers) jest matchers with this code:

```
import targaryen from 'targaryen/plugins/jasmine';

expect.extend(targaryen.matchers);
```

**Comment by fernandopasik** [comment]
Looks like your structure is returning a compare function that later returns what's needed by jest

```
canRead() {

    return {compare(auth, path, now) {

      const data = targaryen.util.getFirebaseData().as(auth);

      const result = data.read(path, now);

      return {
        pass: result.allowed === true,
        message: targaryen.util.unreadableError(result)
      };

    }};

  },
```

**Comment by dinoboff** [comment]
I meant try without a matcher, using targaryen API directly, to see what's missing, what a matcher could improve:

```js
const targaryen = require('targaryen');

const rules = {
  rules: {
    foo: {
      '.write': 'true'
    }
  }
};
const initialData = {foo: {bar: 1, baz: 2}};
const database = targaryen.database(rules, initialData).with({debug: true});

test('Anyone can update foo', t => {
  // Note that a database, it internal rules and its data layer are immutable;
  // concurrent tests can use the same database
  const {info, allowed, newDatabase} = database.update('/foo', {bar: 2});
  
  // a Jest matcher conditionaly print the debug info.
  console.log(info);
  expect(allowed).toBe(true);

  // Unlike chai matcher, a new matcher could also allow to test the new data
  expect(newDatabase.snapshot('/foo').val()). toEqual({bar: 2, baz: 2});
});
```

**Comment by dinoboff** [comment]
@fernandopasik I suggest you create matcher on one of your project. You would sugget also to use `targaryen.util.*Error` helpers but to avoid the helpers using global values, `targaryen.util.set*` or `targaryen.util.set*`; targaryen only synchronous methods so they can be used safely with concurrent test, but you need reset rules and data between each test.

A matcher for something like:
```js
const rules = {
  rules: {
    foo: {
      '.write': 'auth != null'
    }
  }
};
const initialData = {foo: {bar: 1, baz: 2}};
const database = targaryen.database(rules, initialData).with({debug: true});
const alice = {uid: 'alice'};

test('Authenticated user can read foo', t => {
  expect(database).not.toAllowRead('/foo');
  expect(database.as(alice)).toAllowRead('/foo');
  
  // or jest api allows that
  expect(database).can.not.read('/foo');
  expect(database.as(alice)).can.read('/foo');
});
```

**Comment by dedan** [comment]
You can simply use the Chai matchers within your Jest test suites. I found a [blog post](https://medium.com/@RubenOostinga/combining-chai-and-jest-matchers-d12d1ffd0303) that describes this setup in detail.

And here is an example of a simple test of mine, using targaryen matchers with Chai within Jest.

```js
const targaryen = require('targaryen/plugins/chai')
const chai = require('chai')
global.chaiExpect = chai.expect

const rules = require('../database.rules.json')

chai.use(targaryen)

beforeEach(() => {
  targaryen.setFirebaseData({})
  targaryen.setFirebaseRules(rules)
})

it('should allow everybody to write to betaEmails', () => {
  chaiExpect(null).cannot.read.path('/betaEmails')
})
```

**Comment by fernandopasik** [comment]
Thanks @dedan. I'd like to continue looking into adapting the jasmine matchers to jest.
