### ISSUE TITLE
newData as value instead of object

### ISSUE THREAD

**Issue by benthehenten** [goldibex/targaryen#13]
It appears that Targaryen evaluates newData as the value to be written, instead of an object with {key:value} of the data to be written (as Firebase does).

For example, if I have the collection: 
```
/users/$uid
   - first_name
   - last_name
   - age
```
and I try to write "Ben" to `/users/USER123/first_name` and do the check: `newData.val().length > 0`, Targaryen will evaulate newData as "ben", while in Firebase, it will evaluate newData as ` {'first_name': "Ben"`}, so to do the constraint, I actually need to write: `newData.first_name.val().length > 0`.

**Comment by goldibex** [comment]
Yeah, it turns out I erred in my interpretation of the behavior of the canonical rule parser. This is the same problem as #9.

**Comment by goldibex** [comment]
Working the problem now.

**Comment by benthehenten** [comment]
Thanks! Targaryen has been super useful--thanks for the awesome tool.

**Comment by goldibex** [comment]
@benthehenten can you take a look at this again with Targaryen 2.1.0 and see if the problem persists? I think it was corrected with #27, but I want to be sure.

**Comment by goldibex** [comment]
Closed by #27.
