### ISSUE TITLE
Adding the ability to test operations as an admin

### ISSUE THREAD

**Issue by d3lm** [goldibex/targaryen#141]
It would be great to test all sorts of operations like read, write etc. as an admin. This could be achieved for instance by setting an `admin: true` in the `auth` object that is passed to `expect()`. I am not talking about having `isAdmin` in the firebase security rules but rather simulating the Admin SDK.

**Comment by dinoboff** [comment]
As an admin, Firebase doesn't use the rules; there's nothing to test.

**Comment by d3lm** [comment]
Yes, makes sense. I have figured that as well.
