### ISSUE TITLE
Leading "/" confuses path

### ISSUE THREAD

**Issue by tomlarkworthy** [goldibex/targaryen#2]
"tests": {
    "a": {
      "canRead": [1]
    }
  }

is different to

"tests": {
    "/a": {
      "canRead": [1]
    }
  }

 which can cause issues for people that naturally prepend / to path.

**Comment by goldibex** [comment]
Hi Tom, I'm happy to take a look at that. Can you explain in a bit more detail? Currently the bin/targaryen utility doesn't normalize paths from the keys in the `tests` object; is that what you'd like to see changed.

**Comment by tomlarkworthy** [comment]
just I would expect the path "/a/b" to be the same as "a/b/" or "a/b" like the Firebase clients. My tests were not passing until I dropped the preceding "/" so clearly there is some divergence in how paths are parsed. 

Yes its the keys in the test object in the above. Its not a major deal though.

**Comment by tomlarkworthy** [comment]
I have no idea why I closed that, it's still open
