### ISSUE TITLE
Nested read/write rules not respected

### ISSUE THREAD

**Issue by alexweber** [goldibex/targaryen#33]
Given the following rules:
```js
{
  "rules": {
    ".read": "auth !== null",
    ".write": "auth !== null",
    "users": {
      "$user": {
        ".write": "auth.uid === $user"
      }
    }
  }
}
```
and the following data: 
```js
{
  "users": {
    "3403291b-fdc9-4995-9a54-9656241c835d": {
      "name": "User 1"
    },
    "500f6e96-92c6-4f60-ad5d-207253aee4d3": {
      "name": "User 2"
    }
  }
}
```

This test should pass but fails:
```js
const user1 = { uid: '3403291b-fdc9-4995-9a54-9656241c835d' };
const user2 = { uid: '500f6e96-92c6-4f60-ad5d-207253aee4d3' };

expect(user1).can.write.to.path(`users/${user1.uid}`);
expect(user1).cannot.write.to.path(`users/${user2.uid}`);
```

If i remove the top-level ".write" rule, the test correctly passes as expected which leaves me to conclude that nested read/write rules may not be resolved correctly.

**Comment by sebastianovide** [comment]
hi @alexweber 

.read and .write rules shallower in the database override deeper rules, (https://firebase.google.com/docs/database/security/#section-authorization)

**Comment by alexweber** [comment]
@sebastianovide wow, ok, I apologize, this comes as a bit of a shock to me, I had it working the other way around in an application last year, seems a bit counter-intuitive but it is what it is. Thanks!
