### ISSUE TITLE
Undefined `targaryenChai` variable used in example

### ISSUE THREAD

**Issue by jwngr** [goldibex/targaryen#4]
In your [Chai example code](https://github.com/goldibex/targaryen/blob/master/USAGE.md#chai), you use the variable `targaryenChai` which is not previously defined. I think you just want to use `targaryen` here.

**Comment by goldibex** [comment]
Whoops, changed the API right before release but not the docs...

**Comment by goldibex** [comment]
fixed

**Comment by jwngr** [comment]
Awesome! I love the project by the way. We've been thinking a lot about improving the tooling and testability around security rules and this is the best I've seen. Thanks for creating it.
