### ISSUE TITLE
auth variable types undefined

### ISSUE THREAD

**Issue by mhuebert** [goldibex/targaryen#43]
Hi all,

Currently an expression such as `...child('x/' + auth.uid)` fails because the undefined type of `auth.uid` doesn't satisfy the `+` operator. As it is not possible to predict what kind of values `auth` will contain, I thought to relax the `+` operator such that if one of its arguments is undefined, it will use the type of the other:

https://github.com/goldibex/targaryen/compare/master...mhuebert:patch-2#diff-bcd6f8e4293a19f385ed2148860202e5R189

Thoughts/feedback?

Matt

**Comment by dinoboff** [comment]
Doesn't javascript infer the type to string when the type on both side can't be inferred to number?

Is it different for firebase rule expressions?

**Comment by dinoboff** [comment]
@mhuebert Do you had some failing test to "test/spec/lib/parser/rule.js"?
