### ISSUE TITLE
non-existent properties of auth should be treated as null

### ISSUE THREAD

**Issue by mhuebert** [goldibex/targaryen#60]
A rule like "auth.someNonexistentProperty === null" should pass. Tested in the simulator.

I've pushed a failing test here: https://github.com/mhuebert/targaryen/blob/rule-evaluation/test/spec/lib/ruleset.js#L203

**Comment by dinoboff** [comment]
The issue is with `RuleEvaluator.prototype._evalBinaryExpression`.

Firebase uses strict inequality/equality operator in place of looser operator and so does targaryen. However when one side is null or undefined, we should use a looser operator.

**Comment by mhuebert** [comment]
OK. I also just checked and `auth.x.y.z === null` also returns true in the simulator -- so we need to make sure we don't return `Cannot read property 'z' of undefined` errors.

**Comment by dinoboff** [comment]
Can there be a case like with something else than auth? maybe we can proxy access to auth?
