### ISSUE TITLE
live testing for Firebase parity

### ISSUE THREAD

**Issue by mhuebert** [goldibex/targaryen#63]
I suggest we set up async tests that run against a live Firebase database. We currently have a number of known inconsistencies, and Firebase rule evaluation itself can change without notice.

**Comment by dinoboff** [comment]
#91 has some limitation:

- It uses the REST API.
- it uses the legacy secret key authentication.
- It's very slow to run. It only record evaluation of some rules from a live Firebase DB in `test/spec/lib/parser/fixtures.json`.
- it doesn't test a read or write test. It only test how a rule is parsed and evaluated by Firebase; it doesn't test which rules should be read during a read/write operation.

@mhuebert is it ok?

**Comment by dinoboff** [comment]
There's now a daily cron job checking behaviour changes targaryen assumptions about the parser.

**Comment by mhuebert** [comment]
Very happy to see this in here! 👍
